// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnjaj1LCq6pYfhXzb-tu_U4SBK23gzaA',
    appId: '1:1082371004893:web:b7ba688b0d7be867577e34',
    messagingSenderId: '1082371004893',
    projectId: 'noteapp-f923b',
    authDomain: 'noteapp-f923b.firebaseapp.com',
    storageBucket: 'noteapp-f923b.firebasestorage.app',
    measurementId: 'G-735WW1QN97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT5D1pHJjKLScDwFB7RJqpnOcCgPE9CPw',
    appId: '1:1082371004893:android:e5911bcf3bf820f6577e34',
    messagingSenderId: '1082371004893',
    projectId: 'noteapp-f923b',
    storageBucket: 'noteapp-f923b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvOSLjI7y1DjblC4BVO30ZqomYXoyQuu4',
    appId: '1:1082371004893:ios:6fcd2c62fcbc8808577e34',
    messagingSenderId: '1082371004893',
    projectId: 'noteapp-f923b',
    storageBucket: 'noteapp-f923b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvOSLjI7y1DjblC4BVO30ZqomYXoyQuu4',
    appId: '1:1082371004893:ios:6fcd2c62fcbc8808577e34',
    messagingSenderId: '1082371004893',
    projectId: 'noteapp-f923b',
    storageBucket: 'noteapp-f923b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHnjaj1LCq6pYfhXzb-tu_U4SBK23gzaA',
    appId: '1:1082371004893:web:7ad7a11501dc4461577e34',
    messagingSenderId: '1082371004893',
    projectId: 'noteapp-f923b',
    authDomain: 'noteapp-f923b.firebaseapp.com',
    storageBucket: 'noteapp-f923b.firebasestorage.app',
    measurementId: 'G-4VBQSRQWYB',
  );
}
